"""Git hook generation."""
from __future__ import annotations

import logging
import os
import stat
from datetime import datetime
from pathlib import Path

log = logging.getLogger(__name__)


def generate_post_commit_hook(
    repo_root: Path,
    git_dir: Path,
    python_path: str,
    context_name: str
) -> None:
    """
    Generate post-commit hook with PowerShell wrapper.

    Creates:
    - .git/hooks/post-commit (shell script)
    - .chinvex/post-commit.ps1 (PowerShell script)

    Args:
        repo_root: Repository root directory
        git_dir: .git directory path
        python_path: Resolved Python executable path
        context_name: Context name for this repo
    """
    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)

    chinvex_dir = repo_root / ".chinvex"
    chinvex_dir.mkdir(parents=True, exist_ok=True)

    # Backup existing hook if present
    hook_file = hooks_dir / "post-commit"
    if hook_file.exists():
        _backup_existing_hook(hook_file)

    # Generate PowerShell wrapper
    ps_script = chinvex_dir / "post-commit.ps1"
    _generate_powershell_script(ps_script, python_path, context_name)

    # Generate shell hook
    _generate_shell_hook(hook_file, repo_root, ps_script)

    log.info(f"Generated post-commit hook for {context_name}")


def _backup_existing_hook(hook_file: Path) -> None:
    """Backup existing hook with timestamp."""
    timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
    backup_path = hook_file.parent / f"post-commit.bak.{timestamp}"
    hook_file.rename(backup_path)
    log.warning(f"Backed up existing hook to {backup_path.name}")


def _generate_powershell_script(
    ps_script: Path,
    python_path: str,
    context_name: str
) -> None:
    """Generate PowerShell script that performs ingest."""
    # Normalize path for PowerShell
    python_normalized = str(Path(python_path)).replace("\\", "/")

    content = f"""# Generated by chinvex hook install
# Context: {context_name}
# Python path resolved at install time
$ErrorActionPreference = "SilentlyContinue"

# Get changed files from last commit
$changedFiles = git diff --name-only HEAD~1 2>$null
if (-not $changedFiles) {{
    # First commit, use all files
    $changedFiles = git ls-files 2>$null
}}

# Convert to paths argument
$pathsArg = ($changedFiles -join ',')

# Trigger ingest in background
if ($pathsArg) {{
    Start-Process -NoNewWindow -FilePath "{python_normalized}" `
        -ArgumentList "-m","chinvex.cli","ingest","--context","{context_name}","--paths",$pathsArg,"--quiet" `
        -RedirectStandardOutput "NUL" `
        -RedirectStandardError "NUL"
}}
"""

    ps_script.write_text(content, encoding="utf-8")
    log.info(f"Generated PowerShell script: {ps_script}")


def _generate_shell_hook(
    hook_file: Path,
    repo_root: Path,
    ps_script: Path
) -> None:
    """Generate shell hook that calls PowerShell wrapper."""
    # Use relative path from repo root with forward slashes for shell
    rel_ps_path = ps_script.relative_to(repo_root).as_posix()

    content = f"""#!/bin/sh
# Generated by chinvex hook install
# Calls PowerShell for Windows compatibility

# Check if PowerShell script exists
if [ ! -f "{rel_ps_path}" ]; then
    exit 0
fi

# Run PowerShell script in background
pwsh -NoProfile -ExecutionPolicy Bypass -File "{rel_ps_path}" &
exit 0
"""

    hook_file.write_text(content, encoding="utf-8")

    # Make executable (best effort on Windows)
    try:
        current_mode = os.stat(hook_file).st_mode
        os.chmod(hook_file, current_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    except (OSError, NotImplementedError):
        # Windows doesn't fully support Unix permissions
        pass

    log.info(f"Generated shell hook: {hook_file}")
