# tests/state/test_renderer.py
from datetime import datetime, timezone
from chinvex.state.renderer import render_state_md
from chinvex.state.models import StateJson, RecentlyChanged


def test_render_state_md_basic():
    """Test STATE.md rendering with basic data."""
    state = StateJson(
        schema_version=1,
        context="TestContext",
        generated_at=datetime.now(timezone.utc),
        last_ingest_run="run_abc",
        generation_status="ok",
        generation_error=None,
        recently_changed=[
            RecentlyChanged(
                doc_id="doc1",
                source_type="repo",
                source_uri="C:\\test\\file.py",
                change_type="modified",
                changed_at=datetime.now(timezone.utc)
            )
        ],
        active_threads=[],
        extracted_todos=[],
        watch_hits=[],
        decisions=[],
        facts=[],
        annotations=[]
    )

    md = render_state_md(state)

    assert "STATE.md - TestContext" in md
    assert "AUTOGENERATED" in md
    assert "Recently Changed" in md
    assert "file.py" in md
