# src/chinvex/state/renderer.py
from pathlib import Path
from chinvex.state.models import StateJson


def render_state_md(state: StateJson) -> str:
    """
    Render state.json to human-readable markdown.

    Args:
        state: StateJson object to render

    Returns:
        Markdown string for STATE.md
    """
    lines = [
        "<!-- AUTOGENERATED. Edits will be overwritten. Use 'chinvex state note add' for annotations. -->",
        "",
        f"# STATE.md - {state.context}",
        "",
        f"*Generated: {state.generated_at.strftime('%Y-%m-%d %H:%M:%S')}*",
        "",
    ]

    # Generation status warning
    if state.generation_status != "ok":
        lines.append(f"⚠️ **Generation Status:** {state.generation_status}")
        if state.generation_error:
            lines.append(f"*Error: {state.generation_error}*")
        lines.append("")

    # Recently Changed
    if state.recently_changed:
        lines.append("## Recently Changed")
        lines.append("")
        for item in state.recently_changed[:10]:
            name = Path(item.source_uri).name
            ts = item.changed_at.strftime('%Y-%m-%d %H:%M')
            lines.append(f"- `{name}` ({item.source_type}) - {ts}")
        lines.append("")

    # Active Threads
    if state.active_threads:
        lines.append("## Active Threads")
        lines.append("")
        for thread in state.active_threads:
            ts = thread.last_activity.strftime('%Y-%m-%d')
            lines.append(f"- **{thread.title}** - {ts}")
        lines.append("")

    # TODOs
    if state.extracted_todos:
        lines.append("## TODOs")
        lines.append("")
        for todo in state.extracted_todos[:20]:
            name = Path(todo.source_uri).name
            lines.append(f"- [ ] {todo.text} (`{name}:{todo.line}`)")
        lines.append("")

    # Watch Hits
    if state.watch_hits:
        lines.append("## Watch Hits (since last ingest)")
        lines.append("")
        for hit in state.watch_hits:
            lines.append(f"### {hit.watch_id}")
            for chunk in hit.hits[:3]:
                score = chunk.get('score', 0)
                snippet = chunk.get('snippet', '')[:100]
                lines.append(f"- [{score:.2f}] {snippet}...")
        lines.append("")

    # Decisions (if any, from P1.5)
    if state.decisions:
        lines.append("## Decisions")
        lines.append("")
        for dec in state.decisions:
            text = dec.get('text', '')
            date = dec.get('date', '')
            lines.append(f"- {text} ({date})")
        lines.append("")

    # Facts (if any, from P1.5)
    if state.facts:
        lines.append("## Facts")
        lines.append("")
        for fact in state.facts:
            text = fact.get('text', '')
            lines.append(f"- {text}")
        lines.append("")

    # Annotations
    if state.annotations:
        lines.append("## Annotations")
        lines.append("")
        for ann in state.annotations:
            text = ann.get('text', '')
            lines.append(f"- {text}")
        lines.append("")

    return "\n".join(lines)
